services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: juego_educativo
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
